### ISSUE TITLE
Not all nodes was been infected by infected nodes

### ISSUE THREAD

**Issue by guiaugusto** [guiaugusto/the_walking_graph#2]
**Description**

Fixes problems about the generalized infection caused by the chosen node. Only some nodes was been infected, not proliferating to others.

**Tasks**

- [ ] Find the problem about the infection.
- [ ] Treats the recursion stack is collecting all nodes that have to be infected.
- [ ] Tests if a group that a node is infected finished with all elements infected.
